# -*- coding: utf-8 -*-
"""Proyek_Analisis_Data_Arif.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/rifkurniawan-dev/projek_arif/blob/main/Proyek_Analisis_Data_Arif.ipynb

# Proyek Analisis Data: E-Commerce Public Datasat
- **Nama:** Arif Kurniawan
- **Email:** m299d5y1908@student.devacaademy.id
- **ID Dicoding:** MC299D5Y1908

## Pertanyaan

- Bagaimana pengaruh musim terhadap jumlah penyewaan sepeda

- bagaimana pengaruh cuaca terhadap jumlah penyewaan sepeda

## Import Semua Packages/Library yang Digunakan
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""## Data Wrangling

### Gathering Data
"""

day_df = pd.read_csv("day.csv")
day_df.head()

hour_df = pd.read_csv("hour.csv")
hour_df.head()

"""### Assessing Data

Menilai day
"""

day_df.info()

day_df.isna().sum()

print("Jumlah duplikasi: ", day_df.duplicated().sum())

day_df.describe()

"""Menilai Hour"""

hour_df.info()

hour_df.isna().sum()

print("Jumlah duplikasi: ", hour_df.duplicated().sum())

hour_df.describe()

"""### Cleaning Data

Duplicat day
"""

day_df.info()

"""memperbaiki type data"""

datetime_columns = ["dteday"]
for coloumn in datetime_columns:
  day_df[coloumn] = pd.to_datetime(day_df[coloumn])

day_df.head()

"""Duplikat Hour"""

hour_df.info()

"""memperbaiki type data"""

datetime_columns = ["dteday"]
for coloumn in datetime_columns:
  hour_df[coloumn] = pd.to_datetime(hour_df[coloumn])

hour_df.info()

hour_df.head()

"""menggabungkan Hour & day"""

day_hour_df = pd.merge(
    left=hour_df,
    right=day_df,
    how="outer",
    left_on="instant",
    right_on="instant"
)
day_hour_df.head()

day_hour_df.nunique()

day_hour_df.isna().sum()

"""## Exploratory Data Analysis (EDA)

### Explore ...
"""

day_df.sample(5)

day_df.describe(include="all")

day_df.instant.is_unique

day_df.groupby(by='dteday').agg({
    'instant': 'nunique',
    'cnt': ['max', 'min', 'mean', 'std']
})

day_df.groupby(by="season").instant.nunique().sort_values(ascending=False).reset_index()

day_df.groupby(by="weathersit").instant.nunique().sort_values(ascending=False).reset_index()

hour_df.sample(5)

hour_df.describe(include="all")

hour_df.head()

hour_df.groupby(by="instant").cnt.sum()

"""## Explore day_df & hour_df"""

hour_day_df = pd.merge(
      left=hour_df,
      right=day_df,
      how="left",
      left_on="instant",
      right_on="instant"
)
hour_day_df.head()

hour_day_df.groupby(by="season_x").instant.nunique().sort_values(ascending=False).head(10).reset_index()

hour_day_df.groupby(by="weathersit_x").instant.nunique().sort_values(ascending=False).head(10).reset_index()

hour_day_df.groupby(by="dteday_x").instant.nunique().sort_values(ascending=False)

hour_day_df["weather_category"] = hour_day_df["weathersit_x"].apply(lambda x: "Clear/Good Weather" if x == 1 else ("Moderate Weather" if x == 2 else "Bad Weather"))

hour_day_df.groupby("weather_category").instant.nunique().sort_values(ascending=False).reset_index()

hour_day_df.to_csv("hour_day.csv", index=False)

"""Menghubungkan semua

## Visualization & Explanatory Analysis

Bagaimana pengaruh musim terhadap jumlah penyewaan sepeda
"""

hour_day_df.sample(5)

day_df.head()

seasonal_influence = hour_day_df.groupby('season_x')['cnt_x'].sum().sort_values(ascending=False).reset_index()
seasonal_influence.head(10)

musim_mapping = {
    1: 'Musim Dingin',
    2: 'Musim Semi',
    3: 'Musim Panas',
    4: 'Musim Gugur'
}
seasonal_influence['Musim'] = seasonal_influence['season_x'].map(musim_mapping)

plt.figure(figsize=(10, 6))
sns.barplot(x='Musim', y='cnt_x', data=seasonal_influence, hue='Musim', dodge=False, palette="Blues")
plt.title('Pengaruh Musim Terhadap Jumlah Penyewaan Sepeda', fontsize=16)
plt.xlabel('Musim', fontsize=14)
plt.ylabel('Total Penyewaan Sepeda', fontsize=14)
plt.legend([], [], frameon=False)
plt.show()

"""bagaimana pengaruh cuaca terhadap jumlah penyewaan sepeda"""

weather_influence = hour_day_df.groupby('weathersit_x')['cnt_x'].sum().sort_values(ascending=False).reset_index()
weather_influence.head(10)

# Mengelompokkan data berdasarkan kondisi cuaca dan menghitung total penyewaan sepeda
weather_influence = hour_day_df.groupby('weathersit_x')['cnt_x'].sum().sort_values(ascending=False).reset_index()

# Menampilkan 10 data teratas
weather_influence.head(10)

# Membuat plot scatter untuk visualisasi
plt.figure(figsize=(10, 6))
sns.scatterplot(x='weathersit_x', y='cnt_x', data=weather_influence, hue='weathersit_x',
                palette={1: 'green', 2: 'yellow', 3: 'blue', 4: 'gray'},
                s=100, alpha=0.6)

# Menambahkan judul dan label
plt.title('Pengaruh Cuaca Terhadap Jumlah Penyewaan Sepeda', fontsize=16)
plt.xlabel('Jenis Cuaca', fontsize=12)
plt.ylabel('Jumlah Penyewaan Sepeda', fontsize=12)

# Menambahkan legenda dengan label yang sesuai
legend_labels = ['Cerah', 'Berawan/Kabut', 'Gerimis', 'Hujan Lebat']
plt.legend(title='Jenis Cuaca', labels=legend_labels)

# Menambahkan grid untuk memudahkan pembacaan
plt.grid(True)

# Menampilkan plot
plt.show()

"""# Conclusion

Conclusion Pertanyaan 1 : Berdasarkan data yang ada, dapat disimpulkan bahwa musim memiliki pengaruh yang signifikan terhadap jumlah penyewaan sepeda. Pada musim panas, jumlah penyewaan sepeda cenderung mencapai titik tertinggi, kemungkinan karena cuaca yang hangat dan kondisi yang ideal untuk bersepeda. Musim semi juga menunjukkan tingkat penyewaan yang tinggi, meskipun mungkin sedikit lebih rendah dibandingkan musim panas. Ketika memasuki musim gugur, jumlah penyewaan sepeda mulai menurun, mungkin karena cuaca yang semakin dingin dan hari yang lebih pendek. Pada musim dingin, jumlah penyewaan sepeda mencapai titik terendah, yang dapat dikaitkan dengan cuaca yang tidak mendukung dan kondisi jalan yang mungkin kurang aman untuk bersepeda. Secara keseluruhan, musim panas dan semi merupakan periode puncak untuk penyewaan sepeda, sementara musim dingin menunjukkan penurunan yang signifikan dalam aktivitas tersebut.

Conclusion Pertanyaan 2 : Berdasarkan data yang ada, dapat disimpulkan bahwa kondisi cuaca memiliki pengaruh yang signifikan terhadap jumlah penyewaan sepeda. Data menunjukkan bahwa pada cuaca cerah, jumlah penyewaan sepeda mencapai titik tertinggi, yaitu 4.0. Hal ini menunjukkan bahwa cuaca cerah sangat mendukung aktivitas bersepeda. Pada kondisi berawan atau berkabut, jumlah penyewaan sepeda sedikit menurun menjadi 3.0, yang masih tergolong tinggi. Ketika cuaca gerimis, jumlah penyewaan sepeda turun menjadi 2.0, menunjukkan bahwa cuaca yang sedikit basah mengurangi minat orang untuk menyewa sepeda. Pada kondisi hujan lebat, jumlah penyewaan sepeda mencapai titik terendah, yaitu 1.0, yang mengindikasikan bahwa cuaca buruk sangat menghambat aktivitas bersepeda. Secara keseluruhan, cuaca cerah dan berawan/kabut merupakan kondisi yang paling mendukung untuk penyewaan sepeda, sementara hujan lebat memiliki dampak negatif yang signifikan terhadap jumlah penyewaan.
"""

