# -*- coding: utf-8 -*-
"""Proyek_Analisis_Data_Arif.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/rifkurniawan-dev/projek_arif/blob/main/Proyek_Analisis_Data_Arif.ipynb

# Proyek Analisis Data: E-Commerce Public Datasat
- **Nama:** Arif Kurniawan
- **Email:** m299d5y1908@student.devacaademy.id
- **ID Dicoding:** MC299D5Y1908

## Pertanyaan

- Bagaimana pengaruh musim terhadap jumlah penyewaan sepeda

- bagaimana pengaruh cuaca terhadap jumlah penyewaan sepeda

## Import Semua Packages/Library yang Digunakan
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""## Data Wrangling

### Gathering Data
"""

day_df = pd.read_csv("day.csv")
day_df.head()

hour_df = pd.read_csv("hour.csv")
hour_df.head()

"""### Assessing Data

Menilai day
"""

day_df.info()

day_df.isna().sum()

print("Jumlah duplikasi: ", day_df.duplicated().sum())

day_df.describe()

"""Menilai Hour"""

hour_df.info()

hour_df.isna().sum()

print("Jumlah duplikasi: ", hour_df.duplicated().sum())

hour_df.describe()

"""### Cleaning Data

Duplicat day
"""

day_df.info()

"""memperbaiki type data"""

datetime_columns = ["dteday"]
for coloumn in datetime_columns:
  day_df[coloumn] = pd.to_datetime(day_df[coloumn])

day_df.head()

"""Duplikat Hour"""

hour_df.info()

"""memperbaiki type data"""

datetime_columns = ["dteday"]
for coloumn in datetime_columns:
  hour_df[coloumn] = pd.to_datetime(hour_df[coloumn])

hour_df.info()

hour_df.head()

"""menggabungkan Hour & day"""

day_hour_df = pd.merge(
    left=hour_df,
    right=day_df,
    how="outer",
    left_on="instant",
    right_on="instant"
)
day_hour_df.head()

day_hour_df.nunique()

day_hour_df.isna().sum()

"""## Exploratory Data Analysis (EDA)

### Explore ...
"""

day_df.sample(5)

day_df.describe(include="all")

day_df.instant.is_unique

day_df.groupby(by='dteday').agg({
    'instant': 'nunique',
    'cnt': ['max', 'min', 'mean', 'std']
})

day_df.groupby(by="season").instant.nunique().sort_values(ascending=False).reset_index()

day_df.groupby(by="mnth").instant.nunique().sort_values(ascending=False).reset_index()

"""eksplor Hour_df"""

hour_df.sample(5)

weather_data = hour_df.groupby(by="weathersit")['cnt'].sum().sort_values(ascending=False).reset_index()

hour_df.sample(5)

hour_df.describe(include="all")

day_df.weathersit.hist()

instant_in_orders_df =  hour_df.instant
day_df["status"] = day_df["instant"].apply(lambda x: "Active" if x in instant_in_orders_df else "Non Active") # Changed instant_in_hour_df to instant_in_orders_df
day_df.sample(5)

day_df.groupby(by="status").instant.count()

"""## Explore day_df & hour_df"""

hour_day_df = pd.merge(
      left=hour_df,
      right=day_df,
      how="left",
      left_on="instant",
      right_on="instant"
)
hour_day_df.head()

hour_day_df.groupby(by="season_x").instant.nunique().sort_values(ascending=False).head(10).reset_index()

hour_day_df.groupby(by="mnth_x").instant.nunique().sort_values(ascending=False).head(10).reset_index()

hour_day_df.groupby(by="dteday_x").instant.nunique().sort_values(ascending=False)

hour_day_df["weather_category"] = hour_day_df["weathersit_x"].apply(lambda x: "Clear/Good Weather" if x == 1 else ("Moderate Weather" if x == 2 else "Bad Weather"))

hour_day_df.groupby("weather_category").instant.nunique().sort_values(ascending=False).reset_index()

hour_day_df.to_csv("hour_day.csv", index=False)

"""Menghubungkan semua

## Visualization & Explanatory Analysis

Bagaimana pengaruh musim terhadap jumlah penyewaan sepeda
"""

hour_day_df.sample(5)

day_df.head()

seasonal_influence = hour_day_df.groupby('season_x')['cnt_x'].sum().sort_values(ascending=False).reset_index()
seasonal_influence.head(10)

musim_mapping = {
    1: 'Musim Dingin',
    2: 'Musim Semi',
    3: 'Musim Panas',
    4: 'Musim Gugur'
}
seasonal_influence['Musim'] = seasonal_influence['season_x'].map(musim_mapping)

plt.figure(figsize=(10, 6))
sns.barplot(x='Musim', y='cnt_x', data=seasonal_influence, hue='Musim', dodge=False, palette="Blues")
plt.title('Pengaruh Musim Terhadap Jumlah Penyewaan Sepeda', fontsize=16)
plt.xlabel('Musim', fontsize=14)
plt.ylabel('Total Penyewaan Sepeda', fontsize=14)
plt.legend([], [], frameon=False)
plt.show()

"""bagaimana pengaruh cuaca terhadap jumlah penyewaan sepeda"""

weather_influence = hour_day_df.groupby('weathersit_x')['cnt_x'].sum().sort_values(ascending=False).reset_index()
weather_influence.head(10)

weather_influence = hour_day_df.groupby('weathersit_x')['cnt_x'].sum().sort_values(ascending=False).reset_index()
weather_mapping = {
    1: 'Cerah/Sedikit Berawan',
    2: 'Berkabut/Berawan',
    3: 'Hujan Ringan/Snow Ringan',
    4: 'Hujan Deras/Snow Lebat'
}
hour_df['weathersit'] = hour_df['weathersit'].map(weather_mapping)
plt.figure(figsize=(12, 6))
sns.boxplot(x='weathersit', y='cnt', data=hour_df)
plt.title('pengaruh Penyewaan Sepeda Berdasarkan Kondisi Cuaca')
plt.xlabel('Kondisi Cuaca (weathersit)')
plt.ylabel('Jumlah Penyewaan Sepeda')
plt.show()

"""# Conclusion

Conclusion Pertanyaan 1 : Berdasarkan data yang ada, dapat disimpulkan bahwa musim memiliki pengaruh yang signifikan terhadap jumlah penyewaan sepeda. Pada musim panas, jumlah penyewaan sepeda cenderung mencapai titik tertinggi, kemungkinan karena cuaca yang hangat dan kondisi yang ideal untuk bersepeda. Musim semi juga menunjukkan tingkat penyewaan yang tinggi, meskipun mungkin sedikit lebih rendah dibandingkan musim panas. Ketika memasuki musim gugur, jumlah penyewaan sepeda mulai menurun, mungkin karena cuaca yang semakin dingin dan hari yang lebih pendek. Pada musim dingin, jumlah penyewaan sepeda mencapai titik terendah, yang dapat dikaitkan dengan cuaca yang tidak mendukung dan kondisi jalan yang mungkin kurang aman untuk bersepeda. Secara keseluruhan, musim panas dan semi merupakan periode puncak untuk penyewaan sepeda, sementara musim dingin menunjukkan penurunan yang signifikan dalam aktivitas tersebut.

Conclusion Pertanyaan 2 : Cuaca memiliki pengaruh signifikan terhadap jumlah penyewaan sepeda. Kondisi cuaca cerah atau sedikit berawan menunjukkan tingkat penyewaan tertinggi, sementara kondisi cuaca buruk seperti hujan atau salju mengakibatkan penurunan penyewaan secara drastis. Semakin ekstrem cuaca, semakin rendah minat masyarakat dalam menyewa sepeda.
"""

